


import BlogPage from '@/components/Blogpage';
import { Metadata } from 'next/types';
import React from 'react'

export const metadata: Metadata = {
  title: "skycandy blogs",
  description: "Generated by create next app",
};

function page() {
  return (
    <div>
      <BlogPage/>
    </div>
  )
}

export default page